### ISSUE TITLE
Scons 2.4.0 not playing along with Chaste

### ISSUE THREAD

**Issue by mobernabeu** [mobernabeu/homebrew-chaste#4]
I tried compiling Chaste with Scons 2.4.0 and I’m getting the error below. This is not an issue with 2.3.4.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/scons/2.4.0/libexec/scons-local/SCons/Action.py", line 1063, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "python/infra/SConsTools.py", line 289, in BuildTest
    process(o)
  File "python/infra/SConsTools.py", line 251, in process
    o._chaste_lock = getattr(o, '_chaste_lock', threading.Lock())
AttributeError: 'File' object has no attribute '_chaste_lock'
scons: building terminated because of errors.
```

Can we make our formula install 2.3.4 until this is fixed upstream?

**Comment by mirams** [comment]
See https://chaste.cs.ox.ac.uk/trac/ticket/2747 for the Chaste issue to fix this.

**Comment by mirams** [comment]
Should be fixed in r25445

**Comment by mobernabeu** [comment]
Thanks for fixing this so quickly, @mirams @jonc125. 

I confirm that compilation with 2.4.0 is working on my end. Closing issue.
